<script setup>
import { ref, nextTick } from 'vue';
import { X } from 'lucide-vue-next';
import BaseButton from '@/components/BaseButton.vue';
import { useMemberStore } from '@/store/member';
import { storeToRefs } from 'pinia';

const store = useMemberStore();

const { selectedMember } = storeToRefs(store);

const emit = defineEmits(['close', 'save']);

const name = ref('');
const soulHarvesters = ref('');
const neighborhood = ref('');
const salvationStatus = ref(false);
const contact = ref('');
const Todaysdate = ref(new Date().toISOString().split('T')[0]);
const monthName = ref(store.monthNames[new Date().getMonth()]);
const today = new Date().toLocaleDateString('fr-FR');
const nameInput = ref(null);

const handleSave = async () => {
  const updates = {
    name: name.value,
    contact: contact.value,
    neighborhood: neighborhood.value,
    soulHarvesters: soulHarvesters.value,
    salvationStatus: salvationStatus.value,
    date: Todaysdate.value,
    month: monthName.value,
  };
  //
  //const newSoul = {
  //  name: name.value,                // required at creation
  //  contact: contact.value,          // required at creation
  //  soulHarvesters: soulHarvesters.value, // required at creation
  //  salvationStatus: salvationStatus.value, // required at creation
  //  date: date.value,                // optional, can default to today
  //  neighborhood: neighborhood.value, // optional but good to have
  //  admin_id: currentAdminId,        // link to the admin creating the soul
  //  month: month.value,              // optional or auto-set
  //  // id is auto-generated by the DB as UUID
  //  // mentor_id and team_id are left empty for later
  //};
  // await store.updateMember(id, updates);
  emit('close');
};

const setFocus = async () => {
  await nextTick();
  nameInput.value?.focus();
};

const close = () => {
  emit('close');
};
defineExpose({ setFocus });
</script>

<template>
  <div class="fixed inset-0 bg-gray-700/50 backdrop-blur-sm flex justify-center items-center z-50">
    <div class="md:w-[40%] bg-white rounded-lg p-6 shadow-xl relative flex flex-col gap-4">
      <div class="flex justify-between items-center">
        <h2 class="text-3xl font-bold text-purple-900 mb-2">Ajouter une âme</h2>
        <X class="size-6 top-4 right-4 cursor-pointer hover:text-red-500" @click="close" />
      </div>
      <div class="flex flex-col gap-3">
        <label class="text-sm font-semibold text-gray-600">Nom</label>
        <input
          ref="nameInput"
          v-model="name"
          type="text"
          class="border border-purple-300 rounded-md px-3 py-2 outline-none focus:ring-2 focus:ring-purple-400"
        />

        <label class="text-sm font-semibold text-gray-600">Gagneur d'âmes</label>
        <input
          v-model="soulHarvesters"
          type="text"
          class="border border-purple-300 rounded-md px-3 py-2 outline-none focus:ring-2 focus:ring-purple-400"
        />

        <label class="text-sm font-semibold text-gray-600">Quartier</label>
        <input
          v-model="neighborhood"
          type="text"
          class="border border-purple-300 rounded-md px-3 py-2 outline-none focus:ring-2 focus:ring-purple-400"
        />
        <label class="text-sm font-semibold text-gray-600">Contact</label>
        <input
          v-model="contact"
          type="text"
          class="border border-purple-300 rounded-md px-3 py-2 outline-none focus:ring-2 focus:ring-purple-400"
        />

        <label class="text-sm font-semibold text-gray-600">Sauvé</label>
        <select
          v-model="salvationStatus"
          class="border border-purple-300 rounded-md px-3 py-2 outline-none focus:ring-2 focus:ring-purple-400"
        >
          <option :value="true">Oui</option>
          <option :value="false">Non</option>
        </select>
      </div>

      <div class="flex justify-end gap-4 mt-6">
        <BaseButton variant="tertiary" @click="close">Annuler</BaseButton>
        <BaseButton variant="primary" @click="handleSave"> Enregistrer </BaseButton>
      </div>
    </div>
  </div>
</template>
